### ISSUE TITLE
thanks and reference to your guide

### ISSUE THREAD

**Issue by Crashedmind** [weedySeaDragon/plantuml-documentation#10]
hi @weedySeaDragon,
I wanted to thank you for your work on this plantuml guide! :+1: 

I came across it when I was writing a guide to using plantuml stdlib (i.e. icons) : https://crashedmind.github.io/PlantUMLHitchhikersGuide/ (due for first release next week)

I ref'd your page https://plantuml-documentation.readthedocs.io/en/latest/formatting/color-names.html in https://crashedmind.github.io/PlantUMLHitchhikersGuide/color/color.html

Let me know if this is ok/not ok and I can update as req'd.

Overall, I'm collaborating with Arnaud (who wrote Plantuml) to write the guide (as a fan/user of plantuml).

thanks,
Chris

**Comment by weedySeaDragon** [comment]
That's just fine with me, @Crashedmind .  (More documentation is always better.)
Thanks for checking!

**Comment by Crashedmind** [comment]
:+1:  thanks @weedySeaDragon 
release candidate of page is https://crashedmind.github.io/PlantUMLHitchhikersGuide/color/color.html
