### ISSUE TITLE
Edit on GitHub link is broken

### ISSUE THREAD

**Issue by studgeek** [weedySeaDragon/plantuml-documentation#6]
FYI, "Edit on GitHub" on https://plantuml-documentation.readthedocs.io/en/latest/advanced-use/index.html is broken.

**Comment by weedySeaDragon** [comment]
Ya -- that automatically generated URL includes `... /blob/....` which is always broken.  I don't know why it's done that way.

I'll see if there's anything I can do about it.

Thanks for catching it!

**Comment by cometsong** [comment]
The link points to _blob/**origin**/master_ but the actual URL does not have **origin** in it.
https://github.com/weedySeaDragon/plantuml-documentation/blob/master/src/site/sphinx/this_site/index.rst

**Comment by weedySeaDragon** [comment]
This is a known issue with Github urls.
